trigger:
- main

pool:
  name: 'remote-servers'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    version: '6.x'
- script: dotnet build --configuration $(buildConfiguration)  
  displayName: 'dotnet build $(buildConfiguration)' 

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- bash: echo hello world
