trigger:
- main

pool:
  name: 'remote-servers'

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build --configuration $(buildConfiguration)  
    displayName: 'dotnet build $(buildConfiguration)' 

  - bash: echo hello world

