pool:
  name: 'vRED-SE01'

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build --configuration $(buildConfiguration)  
    displayName: 'dotnet build $(buildConfiguration)' 

  - bash: echo hello world

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: '$(serviceLocation)/**/*.csproj'
      includeNuGetOrg: true
