trigger:
- main

pool:
  name: 'remote-servers'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    version: '6.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build --configuration $(buildConfiguration)  
    displayName: 'dotnet build $(buildConfiguration)' 

  - bash: echo hello world